### ISSUE TITLE
Any EN docs?

### ISSUE THREAD

**Issue by ivan-nginx** [zhuzhuyule/HexoEditor#1]
Can u add any English documentation, especially how to install it under the desktop CentOS 7?

**Comment by zhuzhuyule** [comment]
i will have try add.

if you want use it in Linux ,you can download repository and try run it !
```
npm install
npm start
```

i will try to test in Linux !

**Comment by ivan-nginx** [comment]
@zhuzhuyule ueah, i use CentOS 7 in my Desktop machine. For now i edit markdown (and other files) in Visual Studio Code. But if this tool is cool, i'll use it.

**Comment by zhuzhuyule** [comment]
yes! i modify  [MoeEditor](https://github.com/Moeditor/Moeditor), it's use [Electron ](https://electronjs.org/)to run it !

**Comment by ivan-nginx** [comment]
Ok, got it. Will test it some later, after full NexT rebase.

Thank's and HNY!

**Comment by zhuzhuyule** [comment]
thank's and HNY too !

**Comment by ivan-nginx** [comment]
Docs was added.
