### ISSUE TITLE
mac下打开文件再保存,文件名会变化

### ISSUE THREAD

**Issue by zmwxiaoming** [zhuzhuyule/HexoEditor#10]
mac上的一篇文章,本来叫做2018-01-11.md,用HexoEditor的Open打开编辑,然后保存之后变成了文章的title , 请帮忙确认一下

**Comment by zhuzhuyule** [comment]
计划取消自动更改文件名，使用右键设置文件名。

**Comment by zhuzhuyule** [comment]
已经修复： https://github.com/zhuzhuyule/HexoEditor/commit/748bfe0004828cda84589fc2cbe0791ff03f42b2
