### ISSUE TITLE
一个关于Tab和空格缩进的问题

### ISSUE THREAD

**Issue by MonoLogueChi** [zhuzhuyule/HexoEditor#11]
![](https://t1.aixinxi.net/o_1c3n9t7vv14jc114ku7i1ump1h77a.png-w.jpg)

Win64版，下载下来想简单的测试一下，发现了貌似代码块里空格和Tab缩进是不一样的，习惯Tab缩进的
感觉有点不太习惯。

后来又在设置里更改了Tab大小，发现默认设置的是4，改到8才可以对齐，也就是说默认的一个Tab键相当于8个空格，这里的逻辑有点搞不懂？

**Comment by zhuzhuyule** [comment]
已经优化了，感谢提供线索。

优化内容：
输入 `Tab` 自动转换为响应设置个数的 `空格`
