### ISSUE TITLE
[Feature] Add support for Tencent Cloud Object Storage(COS)

### ISSUE THREAD

**Issue by tinpont** [zhuzhuyule/HexoEditor#15]
@zhuzhuyule Could you please add cos support for image upload?

Here is the [document](https://cloud.tencent.com/document/product/436/12260) and here is the [npm package](https://github.com/tencentyun/cos-js-sdk-v5)

**Comment by zhuzhuyule** [comment]
Wait for me to tidy up the code!

![](https://i.loli.net/2018/01/27/5a6bd7b8a9fa7.png)
