### ISSUE TITLE
bug:导出 html 或 pdf  失败并强退, 另外建议提供 修改渲染后代码块中字体大小 的功能

### ISSUE THREAD

**Issue by NotAlwaysRignt** [zhuzhuyule/HexoEditor#17]
操作系统: Ubuntu 16 
下载版本:  HexoEditor_1.3.26_linux_x64.tar.gz
问题: 使用 "导出为HTML" 或 "导出为pdf" 功能时强退
          预览模式时有时图片会不能渲染

另外建议在"设置" 的"渲染"部分可以增加一个调节代码块内字体大小的功能,默认的代码块内部的字体大小太小了.当然通过自定义CSS可以修改,但估计大多数人都不知道怎么改,我是添加了下面一段CSS,修改了font-size的值来修改大小的,不知道有没有更好的方法
#container .highlight pre, #container pre {
    padding: 16px;
    overflow: auto;
    font-size: 150%;
    line-height: 1.45;
    background-color: #f7f7f7;
    border-radius: 3px;
}

最后感谢作者分享,很不错的一款软件

**Comment by zhuzhuyule** [comment]
> 操作系统: Ubuntu 16
下载版本: HexoEditor_1.3.26_linux_x64.tar.gz
问题: 使用 "导出为HTML" 或 "导出为pdf" 功能时强退
预览模式时有时图片会不能渲染

这个我再测测。
> 另外建议在"设置" 的"渲染"部分可以增加一个调节代码块内字体大小的功能,默认的代码块内部的字体大小太小了.

这个只能通过css去修改 ，设置太多反而无从下手。
