### ISSUE TITLE
Mac 下无法new post

### ISSUE THREAD

**Issue by YazhouHao** [zhuzhuyule/HexoEditor#18]
在Mac平台下，采用最新发布的稳定版hexoeditor，点击 new post无法生成hexo post 文件 head部分内容。
点击之后没有反应。
请问这是什么问题呢？

**Comment by zhuzhuyule** [comment]
请确认是否点击该设置：
![20180207013253106.png](https://i.loli.net/2018/02/07/5a7a8fa11249b.png)
`Hexo配置文件`：设置为 **站点配置** 文件 `_config.yml`

**Comment by YazhouHao** [comment]
谢谢!已经按照提示解决了。
