### ISSUE TITLE
程序界面切换时黑屏 右键时屏幕画面偏移(win 10)

### ISSUE THREAD

**Issue by hundan2020** [zhuzhuyule/HexoEditor#19]
你好，我遇到了以下两个问题，尽管不清楚是否是目前环境中其他软硬件导致的，但我还是希望在此询问一下是否有解决或者缓解的办法。
### 程序界面切换时黑屏
若当前正在操作一个最大化的chrome（或其他任意窗口），当从chrome界面切换到HexoEditor时，将有较大几率产生黑屏（Windows仍在运行，但屏幕无法显示），在盲操作切换回chrome后，屏幕恢复正常，再次切换为HexoEditor依然黑屏。
该操作导致的黑屏，由鼠标左键点击任务栏中的HexoEditor触发的几率较大，而由`Alt+Tab`切换触发的几率较小。
若当前运行HexoEditor时，Windows没有可视的其他任何最大化窗口，即HexoEditor程序的该问题不被触发。
问题触发还有一些未知的条件。

![tim 20180213215937](https://user-images.githubusercontent.com/9510938/36153450-40506524-1109-11e8-8179-43508added54.png)

（如图所示，切换至HexoEditor时，将有几率导致黑屏）

### 右键时屏幕画面偏移
当在编辑区点击右键时，可以明显感受到屏幕画面向右略微偏移了1-2像素，同时在窗口左侧阴影变成了明显的黑边，但与黑屏问题一样，问题似乎与显示器画面渲染有关，屏幕上看的到，但是无法通过截图表明。以下截图红色部分的位置为显示器上看到的黑边。

![2](https://user-images.githubusercontent.com/9510938/36154036-1b047024-110b-11e8-8af8-857eeee8c4c4.png)

### 问题补充
黑屏问题与[chrome黑屏问题](https://www.baidu.com/s?ie=UTF-8&wd=chrome%E9%BB%91%E5%B1%8F)非常的相似，因此怀疑与GPU在一定程度上有关。

Windows的x32 x64两个版本都存在该问题。

Moeditor的最后x64版本没有以上两个问题。

### 测试环境
windows 10 x64 家庭版 版本1709
联系笔记本，核显。

如果需要不同的参数信息，我会及时的回复，感谢您的解答。

**Comment by zhuzhuyule** [comment]
加入到群，给我远程看看吧，我这里到没有产生或者说没有重现。

**Comment by zhuzhuyule** [comment]
@hundan2020 嗨，在吗？能否响应我的远程？

**Comment by hundan2020** [comment]
你好，我在群里私聊过你了，但是并没有得到回应。但是这个问题无法通过远程查看，截图是正常的，开启视频录制时显示的也是正常的。我只有通过手机录制电脑屏幕才能把这个情况展示出来。如果需要的话，我会在群里响应。

**Comment by zhuzhuyule** [comment]
系统问题，程序无法提供很好解决方案呢。
