### ISSUE TITLE
希望云储存图床支持自定义域名

### ISSUE THREAD

**Issue by hundan2020** [zhuzhuyule/HexoEditor#20]
很多时候，我们可能更希望使用自定义的域名去取代七牛、腾讯云所提供的自带域名，但是HexoEditor并没有提供修改，希望能够增加该功能

![3](https://user-images.githubusercontent.com/9510938/36154778-72ab2ed8-110d-11e8-8e02-66fd265e7c74.png)

**Comment by zhuzhuyule** [comment]
HexoEditor 会自动获取服务端数据，如果已经在服务端设置好了自定义域名，HexoEditor也会一并获取下来，手动选择即可。

**Comment by hundan2020** [comment]
七牛云能获取自定义域名，腾讯云不行

**Comment by zhuzhuyule** [comment]
已添加这个优化。新增自定义功能。详见 [v1.5.28](https://github.com/zhuzhuyule/HexoEditor/releases )
