### ISSUE TITLE
不能输入中文

### ISSUE THREAD

**Issue by zev3n** [zhuzhuyule/HexoEditor#21]
使用fcitx的搜狗拼音和谷歌拼音都无法输入中文，完全不显示候选列表，没有响应

**Comment by zhuzhuyule** [comment]
请提供截图，还有尝试在浏览器中是否也有此现象，重启电脑是否必现？

**Comment by zhuzhuyule** [comment]
@zev3n 如果无法重现了，请关闭或回复。
