### ISSUE TITLE
ubuntu 16.04无法打开项目路径

### ISSUE THREAD

**Issue by lgl88911** [zhuzhuyule/HexoEditor#22]
ubuntu 16.04下用deb安装，
打开Hexo项目路径无法确认
无法打开全部图片路径

**Comment by lgl88911** [comment]
HexoEditor v1.5.28-Bate我这边编译不过，请问方便提供deb吗，谢谢

**Comment by zhuzhuyule** [comment]
@lgl88911 近期修复Bug后提供 Linux 新包。
