### ISSUE TITLE
关于自定义一个栏

### ISSUE THREAD

**Issue by Qifcn** [zhuzhuyule/HexoEditor#26]
大佬你好可能这个功能是一个很简单的功能  
我希望自定义一些东西，比如说我希望每次新建文章都一些已经设置好的内容
比如说hexo的一些开头的东西可能描述不太清楚我会附上图片
![qq 20180324184629](https://user-images.githubusercontent.com/34029055/37863127-b49385c6-2f93-11e8-9427-daa152e9edf1.png)
比如说我新建一个文章开头就有了
---
title:
tags:
date:时间我希望可以读取系统当前时间精确到秒
---

可惜我没代码能力只能寄希望于作者你了谢谢你在百忙之中的阅读

**Comment by BillYang2016** [comment]
现在支持啊，在\scaffolds文件夹里自定义即可

**Comment by zhuzhuyule** [comment]
@Qifcn 
修改 `工程目录/scaffolds/post.md` 文件即可。
