### ISSUE TITLE
Bold/Italic/Delete/Comment switching issue for multiple lines.

### ISSUE THREAD

**Issue by BillYang2016** [zhuzhuyule/HexoEditor#27]
This is an issue for selecting multiple lines , it's OK for single line.
# Expected behavior
Press `Ctrl` + `B` once for adding `**`.
Press `Ctrl` + `B` twice for removing `**`.

# Actual behavior
This is the original code:
![image](https://user-images.githubusercontent.com/26852391/37974060-7953ed16-320e-11e8-8f9c-1ab8f5affd44.png)
Select all and press Ctrl + B:
![image](https://user-images.githubusercontent.com/26852391/37974098-915a6e08-320e-11e8-8c94-5009af340837.png)
After pressed Ctrl + B twice:
![image](https://user-images.githubusercontent.com/26852391/37974101-94802ac8-320e-11e8-9765-ddd78347c63e.png)
After pressed Ctrl + B three times:
![image](https://user-images.githubusercontent.com/26852391/37974118-a44a168a-320e-11e8-8944-5ee5906bb504.png)

**Comment by zhuzhuyule** [comment]
@BillYang2016 
Fix in [v1.5.30 ](https://github.com/zhuzhuyule/HexoEditor/releases/tag/v1.5.30)
Thank you very much!
