### ISSUE TITLE
上传图片以后文件名不变

### ISSUE THREAD

**Issue by wyf0912** [zhuzhuyule/HexoEditor#29]
你好 我把图片上传到腾讯云或者 SM.MS 后，文件名没有变化

**Comment by zhuzhuyule** [comment]
使用的那个版本以及能否提供截图呢？

**Comment by wyf0912** [comment]
版本是1.5.29
![1](https://user-images.githubusercontent.com/26561397/38562752-dd5cf762-3d0d-11e8-826f-07d50b110008.jpg)
打开腾讯云发现文件的确是上传成功了

**Comment by wyf0912** [comment]
![image](https://user-images.githubusercontent.com/26561397/38562845-152f179c-3d0e-11e8-8034-e4d2d55c2e04.png)
刚才的图片似乎没有上传成功。。我再发一张

**Comment by zhuzhuyule** [comment]
没有看出来哪里有问题呀？自动生成的图片是按照时间戳生成的。（图片名称为:[时间戳].png）
除非手动修改图片名才会更改图片名称（ctrl+单击）,即可修改。

**Comment by zhuzhuyule** [comment]
上传过程是不会去修改本地图片名称的，只有手动修改图片名称，才会改变本地图片的图片名称的。
