### ISSUE TITLE
转义字符无效

### ISSUE THREAD

**Issue by WildSaCk** [zhuzhuyule/HexoEditor#30]
# 单行代码中的转义字符无效，同样一段代码在小书匠中显示正常
- 这是在HexoEditor中的截图
![_ _20180414231023](https://user-images.githubusercontent.com/19181019/38769680-5670a134-4039-11e8-8886-322efc3a002e.png)
- 这是在小书匠中的截图
![_ _20180414231345](https://user-images.githubusercontent.com/19181019/38769693-804a94e2-4039-11e8-8152-685d325eca12.png)

**Comment by zhuzhuyule** [comment]
1. 这是编译Markdown的编译引擎不同导致的，HexoEditor使用的是Marked渲染的(保持与Hexo渲染引擎相同)，对于这种特殊字符的转义应该使用：

| 字符       | 十进制   | 转义字符 |
| :--------: | :------: | :------: |
| "          | `&#34;`  | `&quot;` |
| &          | `&#38;`  | `&amp;`  |
| <          | `&#60;`  | `&lt;`   |
| >          | `&#62;`  | `&gt;`   |
| 不断开空格 | `&#160;` | `&nbsp;` |

2. 请注意，在使用Markdown语法时，在表达式之后 额外添加一个空格，以保持通用性。如：
`>class MyAsyncTask:AsyncTask\<String,Int,Boolean\>(){}`
替换为：
`> class MyAsyncTask:AsyncTask&lt;String,Int,Boolean&gt;(){}`
展示效果：
> class MyAsyncTask:AsyncTask&lt;String,Int,Boolean&gt;(){}

**Comment by WildSaCk** [comment]
好的 了解了
