### ISSUE TITLE
Linux 下上传七牛云提示 undefined

### ISSUE THREAD

**Issue by ocswor** [zhuzhuyule/HexoEditor#33]
![image](https://user-images.githubusercontent.com/8704928/39866885-03a12b94-5485-11e8-9a5e-020da2b73bdc.png)

如图所示，图床的功能，能否做成像git 一样，直接copy就可以直接上传了。

**Comment by zhuzhuyule** [comment]
设置完毕以后重启一下试试，还有没有这样的问题了？

**Comment by ocswor** [comment]
@zhuzhuyule  感谢，重启之后可以了
