### ISSUE TITLE
关于安装..npm run start 之后报错

### ISSUE THREAD

**Issue by Tarhyru** [zhuzhuyule/HexoEditor#35]
报错误..error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory  
但是这个包 libgtk-x11-2.0.so.0
我通过
yum install  libgtk-x11-2.0.so.0 装过了
直接运行
electron .
(electron:4330): Gtk-WARNING **: cannot open display: 
什么原因？怎么解决?
依赖包应该是装全了..到这一步之前还有两个包没装..一一装上直到报这个错误..实在没办法了...
建议在说明里加上需要安装的依赖包

**Comment by MakerGYT** [comment]
解决了吗，我也出现这样问题

**Comment by Zephylaci** [comment]
@MakerGYT 
解决了，这个错误是因为没有图形界面....
再有图形界面的地方运行就好了

**Comment by MakerGYT** [comment]
ee
