### ISSUE TITLE
一个 bug 与一个建议

### ISSUE THREAD

**Issue by Macr0phag3** [zhuzhuyule/HexoEditor#39]
> 1. 均为使用最新版HexoEditor
> 2. 已经阅读过 ReadMe 以及 Closed issues.

你好, 前几天使用了 hexoeditor, 这是一个很棒的编辑器, 各方面都符合我的需求.
使用过程中遇到一个 bug 以及希望向你提出的一个建议:

一个 bug:
Mac 下的hexo 联动模块需使用 hexo 命令:

![image](https://user-images.githubusercontent.com/20874963/41110408-d9ac261c-6aab-11e8-80f0-2de3ca9105c5.png)

但是在 mac 似乎有点问题, 会一直卡在这里不动:
![image](https://user-images.githubusercontent.com/20874963/41110472-0a13c5e4-6aac-11e8-8354-97a4b02372f0.png)

查看 log 发现如下错误:
![image](https://user-images.githubusercontent.com/20874963/41110494-16efea4a-6aac-11e8-8ab0-0f1a8468ff88.png)

但是, 无论是我的默认终端使用的 zsh 还是系统自带的原生sh, 均可以使用 hexo:
![image](https://user-images.githubusercontent.com/20874963/41110531-33636e0e-6aac-11e8-8b9b-c04361bfb973.png)
![image](https://user-images.githubusercontent.com/20874963/41110537-38067550-6aac-11e8-9a33-8c89d512d93c.png)

希望作者能帮我看看是哪个地方出了问题. 

一个建议:
作为一个优秀的 md 编辑文件, 同步滚动必不可少, hexoeditor有, 但是每次启动都需要重新勾选:
![image](https://user-images.githubusercontent.com/20874963/41110642-7a1a9e44-6aac-11e8-95ce-6ebc2f1f671e.png)

希望作者能把它加入到配置中去

以上, 再次感谢如此优秀的编辑器. 👍

**Comment by zhuzhuyule** [comment]
get 等这阵子忙完，就开始研究。
感谢支持。

**Comment by alixez** [comment]
@zhuzhuyule 这个bug应该是electron打包后环境变量有问题。我的解决方案是重写掉PATH变量,
`
// index.js
// on darwin, to rewrite path
// shell-env is https://github.com/sindresorhus/shell-env
if (process.platform === "darwin") {
    const shellEnvs = require('shell-env').sync()
    process.env.PATH = shellEnvs.PATH;
}
`

**Comment by alixez** [comment]
@zhuzhuyule 这个bug是electron build后环境变量有问题，我的解决方案是重写掉PATH：

```javascript
// in index.js
// on darwin, to rewrite path
// shell-env => https://github.com/sindresorhus/shell-env
if (process.platform === "darwin") {
    const shellEnvs = require('shell-env').sync()
    process.env.PATH = shellEnvs.PATH;
}
```
