### ISSUE TITLE
hexo主题无法识别

### ISSUE THREAD

**Issue by charliezcj** [zhuzhuyule/HexoEditor#43]

**Comment by Ellean** [comment]
### 首先，你的描述我的理解
是想说点击➕添加之后并没有出现是吗？
###  然后，我个人对出现此问题的理解
我也遇到了，但是我觉得README写的是仅支持NexT就是说无法再使用其他的主题导入了？
### 最后，还请贡献者能够解释一下

**Comment by charliezcj** [comment]
我之前有一次选择了hexo模式后自动选择了我自己博客的theme，但是之后再也没有出来过

**Comment by Ellean** [comment]
> 我之前有一次选择了hexo模式

你描述的选择Hexo模式应该是这个，但是这个页面并不是用来设置渲染的，也就是`主题设置`.
![default](https://user-images.githubusercontent.com/35844796/43652377-a332a860-9777-11e8-8314-5aad7d9e6904.png)
设置渲染是一下界面，可以在里面设置:

![default](https://user-images.githubusercontent.com/35844796/43652481-ee53bb68-9777-11e8-9f45-3b206ecfeca1.png)

**不过现在看起来支支持NexT**

**Comment by charliezcj** [comment]
要是能够在渲染界面里面找到正确的渲染主题我就不会说了，连自己的渲染主题都没在列表里面，强行修改配置文件也不行

**Comment by Ellean** [comment]
我不是很懂官方文档的意思：
![default](https://user-images.githubusercontent.com/35844796/43653706-72550c70-977b-11e8-9e7d-d86881236847.png)
我的理解是，仅支持NexT主题渲染。

**Comment by charliezcj** [comment]
但是刚刚用了next主题新建了一个博客，却依然发现找不到自己的next主题，我很想知道你是怎么识别到自己的next主题的

**Comment by Ellean** [comment]
>刚才测试了next主题，hexo g可以正常运行但是列表里面还是找不到没有*号的next

带*的也可以正常渲染啊

![20180803205436-0b6a9d442f gif-2-mp4 com](https://user-images.githubusercontent.com/35844796/43657982-f191f4b8-9789-11e8-8ef1-eb63249f7c7f.gif)

**Comment by charliezcj** [comment]
但是这就不能自己修改主题文件了，比如code的字号等等

**Comment by Ellean** [comment]
自定义的话下面的`自定义CSS`应该可以奏效。

**Comment by Menci** [comment]
Why at me?
