### ISSUE TITLE
安装问题求助

### ISSUE THREAD

**Issue by wwwwwalter** [zhuzhuyule/HexoEditor#46]
Downloading electron-v1.8.7-win32-x64.zip
[>                                            ] 1.4% of 50.32 MB (8.39 kB/s)
今天刚看到这个hexo编辑器,看介绍非常好可以大大提高写博客的效率。
but,nmp install，卡在这里了，有没有不翻墙解决的办法？
谢谢！
版主加油💪

**Comment by zhuzhuyule** [comment]
看中文說明呀，使用 cnpm。

**Comment by wwwwwalter** [comment]
谢谢，问题已解决！
![1](https://user-images.githubusercontent.com/41465754/44192750-3a7e7380-a163-11e8-99e5-9a94f649e60e.PNG)
