### ISSUE TITLE
编辑区有序列表序号没有自增

### ISSUE THREAD

**Issue by cooguyan** [zhuzhuyule/HexoEditor#67]
有序列表本应在插入新的表项时，该项之后表项的序号应自增，但是目前看来只有相邻表项的序号自增了。如图：
![深度录屏_moeditor_20190404172008](https://user-images.githubusercontent.com/23098799/55545870-bc2a0e00-5700-11e9-9aa9-0636c069afd0.gif)

正常应该：
![深度录屏_选择区域_20190404171919](https://user-images.githubusercontent.com/23098799/55545901-cfd57480-5700-11e9-867e-192a756b11dc.gif)

奇怪的是只在编辑区有问题，预览区正常。另外我下载Moeditoer测试了一下发现也有一样的问题

**Comment by zhuzhuyule** [comment]
这是 codemirror 的功能，目前HexoEditor 不会修正的。
对于预览区，是应为markdown 渲染引擎会 识别出列表，忽略列表前的数字，所以预览区显示正确。（绝大多数markdown编辑器，阅读器都会优化这个问题的。所以原文件中的数字标示错误，不会显示错误的）
