### ISSUE TITLE
Please provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [zhuzhuyule/HexoEditor#7]
This project is already configured to produce an AppImage for Linux but the AppImage is not available on the project's GitHub Releases page:

https://github.com/zhuzhuyule/HexoEditor/blob/d9643561918fb183420e9fc4b6dbd367d0651851/package.json#L32
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by zhuzhuyule** [comment]
Thank you ! I will have try to do.  If you can help me, I will be very grateful !

**Comment by zhuzhuyule** [comment]
@probonopd  Release have added `appimage` package, please close.

**Comment by probonopd** [comment]
Added to the AppImageHub central directory of available AppImages. Thank you.

**Comment by zhuzhuyule** [comment]
@probonopd  I find this picture[https://appimage.github.io/database/HexoEditor/screenshot.png] is bad !
![](https://appimage.github.io/database/HexoEditor/screenshot.png)

you can use this https://github.com/zhuzhuyule/HexoEditor/blob/master/screenshots/main.png

![](https://github.com/zhuzhuyule/HexoEditor/blob/master/screenshots/main.png)

**Comment by probonopd** [comment]
Hello @zhuzhuyule, the pictures get made by our review system automatically. It is what the application shows directly after it has been launched. If you would like to see another screenshot, please add [AppStream metadata](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) to the AppImage. Thanks.

Here is a generator that can produce it:
http://output.jsbin.com/qoqukof

**Comment by probonopd** [comment]
Example:

```
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
	<id>hexoeditor.appdata.xml</id>
	<metadata_license>CC0-1.0</metadata_license>
	<project_license>GPL-3.0</project_license>
	<name>HexoEditor</name>
	<summary>Markdown editor for Hexo</summary>
	<description>
		<p>Markdown editor for Hexo with features such as Hexo Tag/Filter/Renderer support, custom tag support, _config.yml support, highlight setting, theme tag support and many others.</p>
	</description>
	<launchable type="desktop-id">hexoeditor.desktop</launchable>
	<url type="homepage">https://github.com/zhuzhuyule/HexoEditor</url>
	<screenshots>
		<screenshot type="default">
			<image>https://github.com/zhuzhuyule/HexoEditor/raw/master/screenshots/main.png</image>
		</screenshot>
	</screenshots>
	<provides>
		<id>hexoeditor.desktop</id>
	</provides>
</component>
```

**Comment by scx** [comment]
I created the flatpak package for HexoEditor.
https://github.com/zhuzhuyule/HexoEditor/issues/57
