### ISSUE TITLE
能 release 一个mac 版本么

### ISSUE THREAD

**Issue by ocswor** [zhuzhuyule/HexoEditor#8]
能 release 一个mac 版本么

**Comment by zhuzhuyule** [comment]
我将尝试打包并测试的。如果你能提供环境与测试将非常感谢。

**Comment by normalhh** [comment]
Hi, 我目前MAC版本为：10.13.2 (17C88) 有测试版本的话可以在哪里获取？

**Comment by normalhh** [comment]
@zhuzhuyule Hi, 我目前MAC版本为：10.13.2 (17C88) 有测试版本的话可以在哪里获取？

**Comment by zhuzhuyule** [comment]
@normalhh  目前mac 只能自己编译项目，我目前正在尝试打包 Mac测试版。

或者如果你能够提供帮助，我将非常感谢。

**Comment by wujunze** [comment]
我有兴趣打包个Mac版 并提供运行时测试

**Comment by zhuzhuyule** [comment]
@ocswor @normalhh 
Mac 版本以上线，欢迎试用。

**Comment by zhuzhuyule** [comment]
@wujunze 
非常感谢你的支持，Mac版本以上线，欢迎试用。

如果有兴趣加或者提出一些建议，欢迎PR。
