### ISSUE TITLE
关于同步markdown文件名的问题

### ISSUE THREAD

**Issue by muzi2045** [zhuzhuyule/HexoEditor#9]
在新建一个post以后, 更改默认的文件标题, 
对应的 /source/_posts/ 的文件名会立即同步修改.
但是, 再次修改title以后, .md 文件名无法自动同步
我目前找到的解决办法是关掉当前窗口, 再打开一次该文件, title就会同步到文件名了.
希望可以通过save来直接触发同步操作.
谢谢!

**Comment by zhuzhuyule** [comment]
鼠标右键中有 `同步文件名` 的选项，你试一试。

**Comment by muzi2045** [comment]
OS: win10 x64
安装的最新release安装包, 鼠标右键菜单没有看到同步文件名啊.....

**Comment by zhuzhuyule** [comment]
是这个 ：`HexoEditor1.1.8-win32-x64.exe`  版本吗？
方便再截个图吗？

**Comment by muzi2045** [comment]
![hexo1](https://user-images.githubusercontent.com/12984898/34646674-27aaf480-f3a9-11e7-84f8-6658541302f9.JPG)
![hexo2](https://user-images.githubusercontent.com/12984898/34646675-2b45a61c-f3a9-11e7-8c1e-cdb20ec278a8.JPG)

这是截图

**Comment by muzi2045** [comment]
title我也改过了, 在save的时候, md文件会被同步修改, 可以在文件的修改时间上看出来
但是文件名没有更改, 右键菜单也没有同步文件名的选项出现.

**Comment by zhuzhuyule** [comment]
好奇怪，你下载的是 ia32还是 x64 呢？ 我这里正常的。你重新下载安装试一试看呢？

**Comment by muzi2045** [comment]
谢谢 !
